### ISSUE TITLE
Separate corrral from toritos

### ISSUE THREAD

**Issue by leliel12** [toros-astro/corral#15]
This will be happend soon

**Comment by martinberoiz** [comment]
it will be missed ;)

**Comment by BrunoSanchez** [comment]
it happened already? I didn't see that one coming

El vie., 29 ene. 2016 a las 14:44, Martin Beroiz (<notifications@github.com>)
escribió:

> it will be missed ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toros-astro/corral/issues/15#issuecomment-176881557>.
>
-- 
Bruno

**Comment by leliel12** [comment]
voy a crear un repo comodo con algo de tiempo

On Fri, 29 Jan 2016 at 17:03 Bruno Sánchez <notifications@github.com> wrote:

> it happened already? I didn't see that one coming
>
> El vie., 29 ene. 2016 a las 14:44, Martin Beroiz (<
> notifications@github.com>)
> escribió:
>
> > it will be missed ;)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/toros-astro/corral/issues/15#issuecomment-176881557
> >.
> >
> --
> Bruno
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toros-astro/corral/issues/15#issuecomment-176945638>.
>
-- 

Juan BC (from phone)

**Comment by leliel12** [comment]
lo que se va a mover va a ser toritos no corral

On Fri, 29 Jan 2016 at 17:15 Juan BC <jbc.develop@gmail.com> wrote:

> voy a crear un repo comodo con algo de tiempo
>
> On Fri, 29 Jan 2016 at 17:03 Bruno Sánchez <notifications@github.com>
> wrote:
>
>> it happened already? I didn't see that one coming
>>
>> El vie., 29 ene. 2016 a las 14:44, Martin Beroiz (<
>> notifications@github.com>)
>> escribió:
>>
>> > it will be missed ;)
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/toros-astro/corral/issues/15#issuecomment-176881557
>> >.
>> >
>> --
>> Bruno
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/toros-astro/corral/issues/15#issuecomment-176945638>.
>>
> --
>
> Juan BC (from phone)
>
-- 

Juan BC (from phone)

**Comment by leliel12** [comment]
new home of toritos https://github.com/toros-astro/toritos/
