### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by BrunoSanchez** [toros-astro/corral#16]
Didin't we had requirements already???

Anyway. Please @leliel12  run a pip freeze for me.

**Comment by leliel12** [comment]
but all the requirements are inside setup.py yo need to un pip install -e .

On Tue, 29 Mar 2016 at 21:08 Bruno Sánchez <notifications@github.com> wrote:

> Closed #16 <https://github.com/toros-astro/corral/issues/16>.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/toros-astro/corral/issues/16#event-607516526>
>
-- 

Juan BC (from phone)

**Comment by leliel12** [comment]
the "." dot are important

On Tue, 29 Mar 2016 at 21:41 Juan BC <jbc.develop@gmail.com> wrote:

> but all the requirements are inside setup.py yo need to un pip install -e .
>
> On Tue, 29 Mar 2016 at 21:08 Bruno Sánchez <notifications@github.com>
> wrote:
>
>> Closed #16 <https://github.com/toros-astro/corral/issues/16>.
>>
>> —
>> You are receiving this because you were mentioned.
>>
>>
>> Reply to this email directly or view it on GitHub
>> <https://github.com/toros-astro/corral/issues/16#event-607516526>
>>
> --
>
> Juan BC (from phone)
>
-- 

Juan BC (from phone)
