### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by leliel12** [toros-astro/corral#6]
make a folder inside the *toritos* folder called **data** and upload there at least one ``fits`` file to use as test data. Also an images to use as reference for every step

**Comment by martinberoiz** [comment]
coming soon...

**Comment by martinberoiz** [comment]
It's gonna be 2 images, 6 MB total, is that alright? One image, and one reference.
I also have a subtraction image for that one, but the subtraction will be a byproduct of the pipeline (it's generated by the pipeline, not a real input). The subtraction one is like 6MB but I won't include it. 
If you think it's alright I'll push'em up.
