### ISSUE TITLE
in-corral crashes in clean pull from repo

### ISSUE THREAD

**Issue by martinberoiz** [toros-astro/corral#8]
I just pulled a fresh copy of the repo and tried 

    python in-corral.py

with no commands and it crashes like this.

    Traceback (most recent call last):
      File "in_corral.py", line 10, in <module>
        from corral import cli
      File "/Users/utb/Academia/Research/TOROS/Code/corral_test/corral/corral/cli/__init__.py", line 9, in <module>
        from .. import core, conf, util, exceptions
      File "/Users/utb/Academia/Research/TOROS/Code/corral_test/corral/corral/core.py", line 7, in <module>
        from . import db
      File "/Users/utb/Academia/Research/TOROS/Code/corral_test/corral/corral/db.py", line 16, in <module>
        from . import conf, util
      File "/Users/utb/Academia/Research/TOROS/Code/corral_test/corral/corral/conf.py", line 73, in <module>
        settings = LazySettings(CORRAL_SETTINGS_MODULE)
      File "/Users/utb/Academia/Research/TOROS/Code/corral_test/corral/corral/conf.py", line 35, in __init__
        self._settings = util.dimport(settings_module_name)
      File "/Users/utb/Academia/Research/TOROS/Code/corral_test/corral/corral/util.py", line 43, in dimport
        raise ImportError("No module named {}".format(importpath))
    ImportError: No module named toritos.settings

Can anyone reproduce? Maybe it's just me. I'll look into it in the meantime.

**Comment by leliel12** [comment]
Probably you are not in the same directory that in_corral.py lives (please
also check my email)

On Thu, 5 Nov 2015 at 12:16 Martin Beroiz <notifications@github.com> wrote:

> I just pulled a fresh copy of the repo and tried
>
> python in-corral.py
>
> with no commands and it crashes like this.
>
> Traceback (most recent call last):
>   File "in_corral.py", line 10, in <module>
>     from corral import cli
>   File "/Users/utb/Academia/Research/TOROS/Code/corral_test/corral/corral/cli/__init__.py", line 9, in <module>
>     from .. import core, conf, util, exceptions
>   File "/Users/utb/Academia/Research/TOROS/Code/corral_test/corral/corral/core.py", line 7, in <module>
>     from . import db
>   File "/Users/utb/Academia/Research/TOROS/Code/corral_test/corral/corral/db.py", line 16, in <module>
>     from . import conf, util
>   File "/Users/utb/Academia/Research/TOROS/Code/corral_test/corral/corral/conf.py", line 73, in <module>
>     settings = LazySettings(CORRAL_SETTINGS_MODULE)
>   File "/Users/utb/Academia/Research/TOROS/Code/corral_test/corral/corral/conf.py", line 35, in __init__
>     self._settings = util.dimport(settings_module_name)
>   File "/Users/utb/Academia/Research/TOROS/Code/corral_test/corral/corral/util.py", line 43, in dimport
>     raise ImportError("No module named {}".format(importpath))
> ImportError: No module named toritos.settings
>
> Can anyone reproduce? Maybe it's just me. I'll look into it in the
> meantime.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toros-astro/corral/issues/8>.
>
-- 

Juan BC (from phone)

**Comment by martinberoiz** [comment]
Turns out the toritos module imports numpy, which, if not installed raises an error. This is caught by the try/except block and raises "No module named toritos.settings" which is misleading. The import block could fail by several reasons other than that one.

The raise message should be something like "Problem loading module XXX", what do you guys think?

Also, we should do some kind of setup.py or requirements thingy to install particular toritos dependencies inside toritos (it will have quite a lot of them). I can do that if you bear with me.

**Comment by leliel12** [comment]
Well i need to fix this please open another issue with this description

On Thu, 5 Nov 2015 at 13:46 Martin Beroiz <notifications@github.com> wrote:

> Turns out the toritos module imports numpy, which, if not installed raises
> an error. This is caught by the try/except block and raises "No module
> named toritos.settings" which is misleading. The import block could fail by
> several reasons other than that one.
>
> The raise message should be something like "Problem loading module XXX",
> what do you guys think?
>
> Also, we should do some kind of setup.py or requirements thingy to install
> particular toritos dependencies inside toritos (it will have quite a lot of
> them). I can do that if you bear with me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toros-astro/corral/issues/8#issuecomment-154117936>.
>
-- 

Juan BC (from phone)

**Comment by martinberoiz** [comment]
ok
